name: gromacs-tutorials
channels:
  - conda-forge
  - defaults
dependencies:
  - gromacs=2023.3=nompi*
  - matplotlib
  - nglview=3.1.1
  - mdtraj
  - notebook
  - numpy
  - requests
  - pandas
  - seaborn
  - compilers
  - openmpi
  - cmake
